#!/bin/bash
# LFCS: Users and groups
# Step 2: Personal and system-wide environment profiles
#
# Generated by tools/gen_verifiers.py from tests/questions.json. Do not edit by
# hand: run the generator instead, or the drift check in tests will fail.
#
# The helper is inlined rather than sourced because Killercoda only promises
# the script named in index.json reaches the host.
bad=0

check() { # check <n> <cs|ci> <subject> <accepted answer>...
  local n="$1" mode="$2" subject="$3" a want; shift 3
  a="$(tr -d '[:space:]' < "/tmp/answers/$n" 2>/dev/null)"
  [ "$mode" = ci ] && a="${a,,}"
  [ -n "$a" ] || { echo "question $n ($subject) has no answer recorded" >&2; bad=1; return; }
  for want in "$@"; do
    want="${want// /}"
    [ "$mode" = ci ] && want="${want,,}"
    [ "$a" = "$want" ] && return
  done
  echo "question $n ($subject) is not right yet" >&2
  bad=1
}

check 5 ci 'the page documenting /etc/profile and ~/.bashrc' 'bash'
check 6 ci 'the PAM module that sets environment variables at login' 'pam_env'
check 7 ci 'the configuration page for that module' 'pam_env.conf' 'pam_env.conf(5)'
check 8 ci 'the page defining UMASK and PASS_MAX_DAYS' 'login.defs' '/etc/login.defs'

exit "$bad"
