#!/bin/bash
# LFCS: Users and groups
# Step 3: Configure user resource limits
#
# Generated by tools/gen_verifiers.py from tests/questions.json. Do not edit by
# hand: run the generator instead, or the drift check in tests will fail.
#
# The helper is inlined rather than sourced because Killercoda only promises
# the script named in index.json reaches the host.
bad=0

check() { # check <n> <cs|ci> <subject> <accepted answer>...
  local n="$1" mode="$2" subject="$3" a want; shift 3
  a="$(tr -d '[:space:]' < "/tmp/answers/$n" 2>/dev/null)"
  [ "$mode" = ci ] && a="${a,,}"
  [ -n "$a" ] || { echo "question $n ($subject) has no answer recorded" >&2; bad=1; return; }
  for want in "$@"; do
    want="${want// /}"
    [ "$mode" = ci ] && want="${want,,}"
    [ "$a" = "$want" ] && return
  done
  echo "question $n ($subject) is not right yet" >&2
  bad=1
}

check 9 ci 'the PAM module that applies limits.conf' 'pam_limits'
check 10 ci 'the limits.conf field holding soft or hard' 'type'
check 11 ci 'the limits.conf item capping open file descriptors' 'nofile'
check 12 ci 'the limits.conf item capping the number of processes' 'nproc'

exit "$bad"
