#!/bin/bash
# LFCS: Users and groups
# Step 5: Use LDAP user and group accounts
#
# Generated by tools/gen_verifiers.py from tests/questions.json. Do not edit by
# hand: run the generator instead, or the drift check in tests will fail.
#
# The helper is inlined rather than sourced because Killercoda only promises
# the script named in index.json reaches the host.
bad=0

check() { # check <n> <cs|ci> <subject> <accepted answer>...
  local n="$1" mode="$2" subject="$3" a want; shift 3
  a="$(tr -d '[:space:]' < "/tmp/answers/$n" 2>/dev/null)"
  [ "$mode" = ci ] && a="${a,,}"
  [ -n "$a" ] || { echo "question $n ($subject) has no answer recorded" >&2; bad=1; return; }
  for want in "$@"; do
    want="${want// /}"
    [ "$mode" = ci ] && want="${want,,}"
    [ "$a" = "$want" ] && return
  done
  echo "question $n ($subject) is not right yet" >&2
  bad=1
}

check 1 ci 'the page deciding which sources answer passwd and group lookups' 'nsswitch.conf' '/etc/nsswitch.conf'
check 2 ci 'the section that page lives in' '5'
check 3 ci 'the configuration page for the SSSD daemon' 'sssd.conf' 'sssd.conf(5)'
check 4 ci 'the configuration page for the LDAP client library' 'ldap.conf' 'ldap.conf(5)'

exit "$bad"
