#!/bin/bash
# LFCS: Essential commands
# Step 4: Application and service specific constraints
#
# Generated by tools/gen_verifiers.py from tests/questions.json. Do not edit by
# hand: run the generator instead, or the drift check in tests will fail.
#
# The helper is inlined rather than sourced because Killercoda only promises
# the script named in index.json reaches the host.
bad=0

check() { # check <n> <cs|ci> <subject> <accepted answer>...
  local n="$1" mode="$2" subject="$3" a want; shift 3
  a="$(tr -d '[:space:]' < "/tmp/answers/$n" 2>/dev/null)"
  [ "$mode" = ci ] && a="${a,,}"
  [ -n "$a" ] || { echo "question $n ($subject) has no answer recorded" >&2; bad=1; return; }
  for want in "$@"; do
    want="${want// /}"
    [ "$mode" = ci ] && want="${want,,}"
    [ "$a" = "$want" ] && return
  done
  echo "question $n ($subject) is not right yet" >&2
  bad=1
}

check 13 ci 'the file setting per-user resource limits at login' 'limits.conf' '/etc/security/limits.conf'
check 14 ci 'the section man ulimit actually lands in' '3'
check 15 ci 'the page documenting the shell builtin ulimit' 'bash'
check 16 ci 'the page documenting CPUQuota= and MemoryMax=' 'systemd.resource-control' 'systemd.resource-control(5)'

exit "$bad"
