#!/bin/bash
# LFCS: Essential commands
# Step 6: Work with SSL certificates
#
# Generated by tools/gen_verifiers.py from tests/questions.json. Do not edit by
# hand: run the generator instead, or the drift check in tests will fail.
#
# The helper is inlined rather than sourced because Killercoda only promises
# the script named in index.json reaches the host.
bad=0

check() { # check <n> <cs|ci> <subject> <accepted answer>...
  local n="$1" mode="$2" subject="$3" a want; shift 3
  a="$(tr -d '[:space:]' < "/tmp/answers/$n" 2>/dev/null)"
  [ "$mode" = ci ] && a="${a,,}"
  [ -n "$a" ] || { echo "question $n ($subject) has no answer recorded" >&2; bad=1; return; }
  for want in "$@"; do
    want="${want// /}"
    [ "$mode" = ci ] && want="${want,,}"
    [ "$a" = "$want" ] && return
  done
  echo "question $n ($subject) is not right yet" >&2
  bad=1
}

check 21 ci 'the command suite for certificate operations' 'openssl'
check 22 ci 'the subcommand page for displaying and signing X.509 certificates' 'openssl-x509' 'x509'
check 23 ci 'the command that rebuilds the system trust store' 'update-ca-certificates'
check 24 ci 'the section update-ca-certificates lives in' '8'

exit "$bad"
