#!/bin/bash
# LFCS: Essential commands
# Step 2: Create, configure and troubleshoot services
#
# Generated by tools/gen_verifiers.py from tests/questions.json. Do not edit by
# hand: run the generator instead, or the drift check in tests will fail.
#
# The helper is inlined rather than sourced because Killercoda only promises
# the script named in index.json reaches the host.
bad=0

check() { # check <n> <cs|ci> <subject> <accepted answer>...
  local n="$1" mode="$2" subject="$3" a want; shift 3
  a="$(tr -d '[:space:]' < "/tmp/answers/$n" 2>/dev/null)"
  [ "$mode" = ci ] && a="${a,,}"
  [ -n "$a" ] || { echo "question $n ($subject) has no answer recorded" >&2; bad=1; return; }
  for want in "$@"; do
    want="${want// /}"
    [ "$mode" = ci ] && want="${want,,}"
    [ "$a" = "$want" ] && return
  done
  echo "question $n ($subject) is not right yet" >&2
  bad=1
}

check 5 ci 'the systemctl subcommand that rereads unit files after an edit' 'daemon-reload' 'systemctl daemon-reload'
check 6 cs 'the journalctl flag that limits output to one unit' '-u' '--unit'
check 7 ci 'the page that documents Restart=' 'systemd.service' 'systemd.service(5)'
check 8 ci 'the systemctl subcommand showing a unit'\''s state with recent log lines' 'status' 'systemctl status'

exit "$bad"
