#!/bin/bash
# LFCS prep 2: man page speed drill
# Step 1: SECTIONS (10 answers)
#
# Generated by tools/gen_verifiers.py from tests/questions.json. Do not edit by
# hand: run the generator instead, or the drift check in tests will fail.
#
# The helper is inlined rather than sourced because Killercoda only promises
# the script named in index.json reaches the host.
#
# shellcheck disable=SC2016
# Accepted answers are literal text to compare against, not shell to run, so
# one containing a dollar sign is quoted single deliberately.
bad=0

check() { # check <n> <cs|ci> <subject> <accepted answer>...
  local n="$1" mode="$2" subject="$3" a want; shift 3
  a="$(tr -d '[:space:]' < "/tmp/answers/$n" 2>/dev/null)"
  [ "$mode" = ci ] && a="${a,,}"
  [ -n "$a" ] || { echo "question $n ($subject) has no answer recorded" >&2; bad=1; return; }
  for want in "$@"; do
    want="${want// /}"
    [ "$mode" = ci ] && want="${want,,}"
    [ "$a" = "$want" ] && return
  done
  echo "question $n ($subject) is not right yet" >&2
  bad=1
}

check 1 ci 'fstab' 'man 5 fstab' 'man fstab.5' 'man -s 5 fstab' 'man --sections=5 fstab'
check 2 ci 'admin commands' '8' 'section 8' 'man8' '8)'
check 3 ci 'crontab' 'man 5 crontab' 'man crontab.5' 'man -s 5 crontab'
check 4 ci 'chage' '1' 'section 1' 'man1' '1)'
check 5 ci 'passwd' 'man 5 passwd' 'man passwd.5' 'man -s 5 passwd'
check 6 ci 'read every match' 'man -a passwd' 'man --all passwd' 'man -a -- passwd'
check 7 ci 'sysctl' 'man 8 sysctl' 'man sysctl.8' 'man -s 8 sysctl'
check 8 ci 'sysctl.d drop-ins' 'man 5 sysctl.d' 'man sysctl.d' 'man sysctl.d.5' 'man -s 5 sysctl.d'
check 9 ci 'the filesystem layout' 'man 7 hier' 'man hier' 'man hier.7' 'man -s 7 hier'
check 10 ci 'device files' '4' 'section 4' 'man4' '4)'

exit "$bad"
