#!/bin/bash
# LFCS prep 2: man page speed drill
# Step 5: BEYOND-MAN (9 answers)
#
# Generated by tools/gen_verifiers.py from tests/questions.json. Do not edit by
# hand: run the generator instead, or the drift check in tests will fail.
#
# The helper is inlined rather than sourced because Killercoda only promises
# the script named in index.json reaches the host.
#
# shellcheck disable=SC2016
# Accepted answers are literal text to compare against, not shell to run, so
# one containing a dollar sign is quoted single deliberately.
bad=0

check() { # check <n> <cs|ci> <subject> <accepted answer>...
  local n="$1" mode="$2" subject="$3" a want; shift 3
  a="$(tr -d '[:space:]' < "/tmp/answers/$n" 2>/dev/null)"
  [ "$mode" = ci ] && a="${a,,}"
  [ -n "$a" ] || { echo "question $n ($subject) has no answer recorded" >&2; bad=1; return; }
  for want in "$@"; do
    want="${want// /}"
    [ "$mode" = ci ] && want="${want,,}"
    [ "$a" = "$want" ] && return
  done
  echo "question $n ($subject) is not right yet" >&2
  bad=1
}

check 38 ci 'the other documentation tree' '/usr/share/doc' '/usr/share/doc/' 'usr/share/doc'
check 39 ci 'what did this package install' 'dpkg -L nfs-common' 'dpkg --listfiles nfs-common' 'dpkg-query -L nfs-common'
check 40 ci 'just the documentation' 'rpm -qd chrony' 'rpm -q -d chrony' 'rpm -qd --whatprovides chrony' 'rpm --query --docfiles chrony' 'rpm -q --docfiles chrony'
check 41 ci 'three locations at once' 'whereis nft' 'whereis -b nft'
check 42 ci 'builtin or binary' 'type cd' 'type -a cd' 'command -V cd'
check 43 ci 'which package owns this file, RPM host' 'rpm -qf /etc/chrony.conf' 'rpm -q -f /etc/chrony.conf' 'rpm --query --file /etc/chrony.conf'
check 44 ci 'which package owns this file, Debian host' 'dpkg -S /etc/chrony.conf' 'dpkg --search /etc/chrony.conf' 'dpkg-query -S /etc/chrony.conf'
check 45 ci 'the unit as loaded' 'systemctl cat chronyd' 'systemctl cat chronyd.service'
check 46 ci 'every systemd directive' 'man 7 systemd.directives' 'man systemd.directives' 'man systemd.directives.7' 'man -s 7 systemd.directives'

exit "$bad"
