#!/bin/bash
# LFCS prep 2: man page speed drill
# Step 3: DISCOVERY (10 answers)
#
# Generated by tools/gen_verifiers.py from tests/questions.json. Do not edit by
# hand: run the generator instead, or the drift check in tests will fail.
#
# The helper is inlined rather than sourced because Killercoda only promises
# the script named in index.json reaches the host.
bad=0

check() { # check <n> <cs|ci> <subject> <accepted answer>...
  local n="$1" mode="$2" subject="$3" a want; shift 3
  a="$(tr -d '[:space:]' < "/tmp/answers/$n" 2>/dev/null)"
  [ "$mode" = ci ] && a="${a,,}"
  [ -n "$a" ] || { echo "question $n ($subject) has no answer recorded" >&2; bad=1; return; }
  for want in "$@"; do
    want="${want// /}"
    [ "$mode" = ci ] && want="${want,,}"
    [ "$a" = "$want" ] && return
  done
  echo "question $n ($subject) is not right yet" >&2
  bad=1
}

check 18 ci 'you do not know the command name' 'man -k quota' 'apropos quota' 'man --apropos quota' 'man -k '\''quota'\'''
check 19 ci 'nothing appropriate' 'mandb' 'mandb -c' '/usr/bin/mandb'
check 20 cs 'the brute-force search' 'man -K OnCalendar' 'man --global-apropos OnCalendar' 'man -K '\''OnCalendar'\''' 'man -K oncalendar'
check 21 ci 'what does this thing do' 'whatis ss' 'man -f ss' 'man --whatis ss'
check 22 ci 'narrow the search' 'apropos -s 5 mount' 'man -k -s 5 mount' 'apropos --sections=5 mount' 'apropos -s5 mount' 'man -k -s5 mount' 'apropos --section=5 mount'
check 23 ci 'too many hits' 'apropos -e mount' 'man -k -e mount' 'apropos --exact mount' 'apropos -e '\''mount'\'''
check 24 ci 'both words, not either' 'apropos -a nfs mount' 'man -k -a nfs mount' 'apropos --and nfs mount' 'apropos -a mount nfs' 'man -k -a mount nfs'
check 25 ci 'where does the page live' 'man -w sshd_config' 'man --where sshd_config' 'man --path sshd_config' 'man --location sshd_config' 'man -w 5 sshd_config'
check 26 ci 'anchor the keyword' 'man -k '\''^chage'\''' 'man -k ^chage' 'apropos '\''^chage'\''' 'apropos ^chage' 'man -k "^chage"'
check 27 ci 'where is man looking' 'manpath' 'manpath -g' 'echo $MANPATH'

exit "$bad"
