#!/bin/bash
# LFCS prep 2: man page speed drill
# Step 6: EXAM-LOOKUPS (10 answers)
#
# Generated by tools/gen_verifiers.py from tests/questions.json. Do not edit by
# hand: run the generator instead, or the drift check in tests will fail.
#
# The helper is inlined rather than sourced because Killercoda only promises
# the script named in index.json reaches the host.
#
# shellcheck disable=SC2016
# Accepted answers are literal text to compare against, not shell to run, so
# one containing a dollar sign is quoted single deliberately.
bad=0

check() { # check <n> <cs|ci> <subject> <accepted answer>...
  local n="$1" mode="$2" subject="$3" a want; shift 3
  a="$(tr -d '[:space:]' < "/tmp/answers/$n" 2>/dev/null)"
  [ "$mode" = ci ] && a="${a,,}"
  [ -n "$a" ] || { echo "question $n ($subject) has no answer recorded" >&2; bad=1; return; }
  for want in "$@"; do
    want="${want// /}"
    [ "$mode" = ci ] && want="${want,,}"
    [ "$a" = "$want" ] && return
  done
  echo "question $n ($subject) is not right yet" >&2
  bad=1
}

check 47 ci 'make it persist' 'man 5 sysctl.d' 'man sysctl.d' 'man sysctl.d.5' 'man -s 5 sysctl.d'
check 48 ci 'every monday at 03:00' 'man 7 systemd.time' 'man systemd.time' 'man systemd.time.7' 'man -s 7 systemd.time'
check 49 ci 'the bind mount' 'man 8 mount' 'man mount' 'man mount.8' 'man -s 8 mount'
check 50 ci 'default acl, open the page' 'man setfacl' 'man 1 setfacl' 'man setfacl.1'
check 51 ci 'default acl, inside the page' '/default' '/-d' '&default'
check 52 ci 'rich rules' 'man 5 firewalld.richlanguage' 'man firewalld.richlanguage' 'man firewalld.richlanguage.5' 'man -s 5 firewalld.richlanguage'
check 53 ci 'an nftables rule from scratch, the page' 'man 8 nft' 'man nft' 'man nft.8' 'man -s 8 nft'
check 54 ci 'an nftables rule from scratch, inside the page' '/EXAMPLES' '/EXAMPLE' '&EXAMPLES'
check 55 ci 'journalctl since yesterday' 'man 7 systemd.time' 'man systemd.time' 'man systemd.time.7' 'man -s 7 systemd.time'
check 56 ci 'nmcli, worked' 'man 7 nmcli-examples' 'man nmcli-examples' 'man nmcli-examples.7' 'man -s 7 nmcli-examples'

exit "$bad"
