#!/bin/bash
# LFCS prep 2: man page speed drill
# Step 2: SECTIONS (7 answers)
#
# Generated by tools/gen_verifiers.py from tests/questions.json. Do not edit by
# hand: run the generator instead, or the drift check in tests will fail.
#
# The helper is inlined rather than sourced because Killercoda only promises
# the script named in index.json reaches the host.
bad=0

check() { # check <n> <cs|ci> <subject> <accepted answer>...
  local n="$1" mode="$2" subject="$3" a want; shift 3
  a="$(tr -d '[:space:]' < "/tmp/answers/$n" 2>/dev/null)"
  [ "$mode" = ci ] && a="${a,,}"
  [ -n "$a" ] || { echo "question $n ($subject) has no answer recorded" >&2; bad=1; return; }
  for want in "$@"; do
    want="${want// /}"
    [ "$mode" = ci ] && want="${want,,}"
    [ "$a" = "$want" ] && return
  done
  echo "question $n ($subject) is not right yet" >&2
  bad=1
}

check 11 ci 'sudoers, two pages, the file syntax' 'man 5 sudoers' 'man sudoers' 'man sudoers.5' 'man -s 5 sudoers'
check 12 ci 'sudoers, two pages, the safe editor' 'man 8 visudo' 'man visudo' 'man visudo.8' 'man -s 8 visudo'
check 13 ci 'timer units' 'man 5 systemd.timer' 'man systemd.timer' 'man systemd.timer.5' 'man -s 5 systemd.timer'
check 14 ci 'the directive you cannot find' 'man 5 systemd.exec' 'man systemd.exec' 'man systemd.exec.5' 'man -s 5 systemd.exec'
check 15 ci 'resource limits' 'man 5 limits.conf' 'man limits.conf' 'man limits.conf.5' 'man -s 5 limits.conf'
check 16 ci 'sshd keywords' 'man 5 sshd_config' 'man sshd_config' 'man sshd_config.5' 'man -s 5 sshd_config'
check 17 ci 'nfs mount options' 'man 5 nfs' 'man nfs' 'man nfs.5' 'man -s 5 nfs'

exit "$bad"
