#!/bin/bash
# LFCS prep 2: man page speed drill
# Step 4: PAGER (10 answers)
#
# Generated by tools/gen_verifiers.py from tests/questions.json. Do not edit by
# hand: run the generator instead, or the drift check in tests will fail.
#
# The helper is inlined rather than sourced because Killercoda only promises
# the script named in index.json reaches the host.
#
# shellcheck disable=SC2016
# Accepted answers are literal text to compare against, not shell to run, so
# one containing a dollar sign is quoted single deliberately.
bad=0

check() { # check <n> <cs|ci> <subject> <accepted answer>...
  local n="$1" mode="$2" subject="$3" a want; shift 3
  a="$(tr -d '[:space:]' < "/tmp/answers/$n" 2>/dev/null)"
  [ "$mode" = ci ] && a="${a,,}"
  [ -n "$a" ] || { echo "question $n ($subject) has no answer recorded" >&2; bad=1; return; }
  for want in "$@"; do
    want="${want// /}"
    [ "$mode" = ci ] && want="${want,,}"
    [ "$a" = "$want" ] && return
  done
  echo "question $n ($subject) is not right yet" >&2
  bad=1
}

check 28 ci 'get to the examples' '/EXAMPLES' '/EXAMPLE' '/^EXAMPLES'
check 29 cs 'repeat the search, next match' 'n'
check 30 cs 'repeat the search, previous match' 'N'
check 31 cs 'both ends of the page, end' 'G' '>'
check 32 cs 'both ends of the page, top' 'g' '<'
check 33 ci 'leave' 'q' ':q' 'ZZ'
check 34 cs 'hide everything else' '&noexec' '& noexec'
check 35 cs 'search backwards' '?noexec' '? noexec'
check 36 ci 'the pager'\''s own help' 'h'
check 37 ci 'half a screen' 'Ctrl-d' '^D' '<C-d>' 'ctrl+d' 'ctrl d' 'C-d' 'd'

exit "$bad"
