#!/usr/bin/env python3
"""Generate each scenario's verify<step>.sh from tests/questions.json.

Thirty-four steps across five scenarios all need the same answer-checking
helper, and Killercoda only promises the verify script named in index.json is
on the host, so the helper cannot be sourced from a sibling file. Writing it
into all of them by hand guarantees they drift. This writes them instead.

  python3 tools/gen_verifiers.py           rewrite the verifiers
  python3 tools/gen_verifiers.py --check   fail if any file is out of date

tests/test_questions.py runs the --check form, so a hand-edited verifier is a
test failure rather than a surprise on the live scenario.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "tests" / "questions.json"

HEADER = """#!/bin/bash
# {title}
# Step {step}: {step_title}
#
# Generated by tools/gen_verifiers.py from tests/questions.json. Do not edit by
# hand: run the generator instead, or the drift check in tests will fail.
#
# The helper is inlined rather than sourced because Killercoda only promises
# the script named in index.json reaches the host.
#
# shellcheck disable=SC2016
# Accepted answers are literal text to compare against, not shell to run, so
# one containing a dollar sign is quoted single deliberately.
bad=0

check() {{ # check <n> <cs|ci> <subject> <accepted answer>...
  local n="$1" mode="$2" subject="$3" a want; shift 3
  a="$(tr -d '[:space:]' < "/tmp/answers/$n" 2>/dev/null)"
  [ "$mode" = ci ] && a="${{a,,}}"
  [ -n "$a" ] || {{ echo "question $n ($subject) has no answer recorded" >&2; bad=1; return; }}
  for want in "$@"; do
    want="${{want// /}}"
    [ "$mode" = ci ] && want="${{want,,}}"
    [ "$a" = "$want" ] && return
  done
  echo "question $n ($subject) is not right yet" >&2
  bad=1
}}

"""


def shq(s: str) -> str:
    """Single-quote a value for bash."""
    return "'" + s.replace("'", "'\\''") + "'"


def render(scenario: dict, step: int) -> str:
    title = scenario["title"]
    step_title = scenario["steps"][step - 1]
    out = HEADER.format(title=title, step=step, step_title=step_title)
    for q in scenario["questions"]:
        if q["step"] != step:
            continue
        mode = "cs" if q.get("cs") else "ci"
        accepted = " ".join(shq(a) for a in [q["answer"], *q.get("accept", [])])
        out += f"check {q['n']} {mode} {shq(q['subject'])} {accepted}\n"
    out += "\nexit \"$bad\"\n"
    return out


def main() -> int:
    check_only = "--check" in sys.argv
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    stale, written = [], 0

    for name, scenario in manifest["scenarios"].items():
        steps = {q["step"] for q in scenario["questions"]}
        for step in sorted(steps):
            path = ROOT / name / f"verify{step}.sh"
            want = render(scenario, step)
            have = path.read_text(encoding="utf-8") if path.is_file() else None
            if have == want:
                continue
            if check_only:
                stale.append(str(path.relative_to(ROOT)))
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(want, encoding="utf-8")
                path.chmod(0o755)
                written += 1

    if check_only:
        if stale:
            print("\nFAILED", file=sys.stderr)
            for s in stale:
                print(f"  x {s} does not match the generator", file=sys.stderr)
            print("  run: python3 tools/gen_verifiers.py", file=sys.stderr)
            return 1
        print("  verifiers match tests/questions.json")
        return 0

    print(f"  wrote {written} verifier(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
